#!/bin/sh -e
source vars.sh

# Build floppy image with the Centos kickstart file
hdiutil detach /Volumes/HYDRA-KS/ || true # In case we've been here before
dd if=/dev/zero of=$KICKSTART bs=1024 count=1440
diskutil eraseVolume MS-DOS HYDRA-KS `hdiutil attach -nomount $KICKSTART`
cp ks.cfg /Volumes/HYDRA-KS/ks.cfg	# Kickstart file

# Delete any existing VM and create a new VM from scratch
VBoxManage unregistervm ${NAME} --delete
VBoxManage createvm --name ${NAME} --ostype ${TYPE} --register

VBoxManage modifyvm ${NAME} \
    --vram 12 \
    --accelerate3d off \
    --memory 613 \
    --usb off \
    --audio none \
    --boot1 disk --boot2 dvd --boot3 none --boot4 none \
    --nictype1 virtio --nic1 nat --natnet1 "${NATNET}" \
    --nictype2 virtio \
    --nictype3 virtio \
    --nictype4 virtio \
    --acpi on --ioapic off \
    --chipset piix3 \
    --rtcuseutc on \
    --hpet on \
    --bioslogofadein off \
    --bioslogofadeout off \
    --bioslogodisplaytime 0 \
    --biosbootmenu disabled

VBoxManage createhd --filename "${HDD}" --size 8192
# Swap is recommended to be double the size of RAM. It is a fixed size as
# it is performance sensitive.
VBoxManage createhd --filename "${HDD_SWAP}" --size 4096

VBoxManage storagectl ${NAME} \
    --name SATA --add sata --portcount 2 --bootable on

VBoxManage storageattach ${NAME} \
    --storagectl SATA --port 0 --type hdd --medium "${HDD}"
VBoxManage storageattach ${NAME} \
    --storagectl SATA --port 1 --type hdd --medium "${HDD_SWAP}"
VBoxManage storageattach ${NAME} \
    --storagectl SATA --port 2 --type dvddrive --medium "${INSTALLER}"
# The following line can be removed when this issue resolved: https://www.virtualbox.org/ticket/13040
VBoxManage storageattach ${NAME} \
    --storagectl SATA --port 3 --type dvddrive --medium emptydrive
VBoxManage storageattach ${NAME} \
    --storagectl SATA --port 3 --type dvddrive --medium additions

# Attach a floppy image with the Centos kickstart file
VBoxManage storagectl ${NAME} \
    --name FDC --add floppy --portcount 1 --bootable on
VBoxManage storageattach ${NAME} \
    --storagectl FDC --port 0 --device 0 --type fdd --medium "${KICKSTART}"

VBoxManage startvm ${NAME} --type gui

# Wait 1 seconds and then add the following kickstart config using keyboardputscancode
# inst.ks=hd:fd0:/ks.cfg
sleep 1
VBoxManage controlvm ${NAME} keyboardputscancode 0f 8f
VBoxManage controlvm ${NAME} keyboardputscancode 39 b9 17 97 31 b1 1f 9f 14 94 34 b4 25 a5 1f 9f 0d 8d
VBoxManage controlvm ${NAME} keyboardputscancode 23 a3 20 a0 2a 27 a7 aa 21 a1 20 a0 0b 8b 2a 27 a7 aa 35 b5 25 a5 1f 9f 34 b4 2e ae 21 a1 22 a2 1c 9c

# tab sp i  n  s  t  .  k  s  =  h  d  :     f  d  0  :     /  k  s  .  c  f  g  enter
#  0f 39 17 31 1f 14 34 25 1f 0d 23 20 2a 27 21 20 0b 2a 27 35 25 1f 34 2e 21 22 1c

echo When finished:
echo "./cleanup && vagrant package --base ${NAME} --output boxes/${NAME}-`date -j +%Y%m%d`.box"
